package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PlatoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatoAllPropertiesEquals(Plato expected, Plato actual) {
        assertPlatoAutoGeneratedPropertiesEquals(expected, actual);
        assertPlatoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatoAllUpdatablePropertiesEquals(Plato expected, Plato actual) {
        assertPlatoUpdatableFieldsEquals(expected, actual);
        assertPlatoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatoAutoGeneratedPropertiesEquals(Plato expected, Plato actual) {
        assertThat(actual)
            .as("Verify Plato auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatoUpdatableFieldsEquals(Plato expected, Plato actual) {
        assertThat(actual)
            .as("Verify Plato relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a ->
                assertThat(a.getPrecio()).as("check precio").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrecio())
            )
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPlatoUpdatableRelationshipsEquals(Plato expected, Plato actual) {
        assertThat(actual)
            .as("Verify Plato relationships")
            .satisfies(a -> assertThat(a.getCategorias()).as("check categorias").isEqualTo(expected.getCategorias()));
    }
}
