package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class ContactoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactoAllPropertiesEquals(Contacto expected, Contacto actual) {
        assertContactoAutoGeneratedPropertiesEquals(expected, actual);
        assertContactoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactoAllUpdatablePropertiesEquals(Contacto expected, Contacto actual) {
        assertContactoUpdatableFieldsEquals(expected, actual);
        assertContactoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactoAutoGeneratedPropertiesEquals(Contacto expected, Contacto actual) {
        assertThat(actual)
            .as("Verify Contacto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactoUpdatableFieldsEquals(Contacto expected, Contacto actual) {
        assertThat(actual)
            .as("Verify Contacto relevant properties")
            .satisfies(a ->
                assertThat(a.getFechaContacto())
                    .as("check fechaContacto")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getFechaContacto())
            )
            .satisfies(a -> assertThat(a.getMotivo()).as("check motivo").isEqualTo(expected.getMotivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContactoUpdatableRelationshipsEquals(Contacto expected, Contacto actual) {
        assertThat(actual)
            .as("Verify Contacto relationships")
            .satisfies(a -> assertThat(a.getCliente()).as("check cliente").isEqualTo(expected.getCliente()));
    }
}
