package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InsumoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsumoAllPropertiesEquals(Insumo expected, Insumo actual) {
        assertInsumoAutoGeneratedPropertiesEquals(expected, actual);
        assertInsumoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsumoAllUpdatablePropertiesEquals(Insumo expected, Insumo actual) {
        assertInsumoUpdatableFieldsEquals(expected, actual);
        assertInsumoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsumoAutoGeneratedPropertiesEquals(Insumo expected, Insumo actual) {
        assertThat(actual)
            .as("Verify Insumo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsumoUpdatableFieldsEquals(Insumo expected, Insumo actual) {
        assertThat(actual)
            .as("Verify Insumo relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getStockMinimo()).as("check stockMinimo").isEqualTo(expected.getStockMinimo()))
            .satisfies(a -> assertThat(a.getStockActual()).as("check stockActual").isEqualTo(expected.getStockActual()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInsumoUpdatableRelationshipsEquals(Insumo expected, Insumo actual) {
        assertThat(actual)
            .as("Verify Insumo relationships")
            .satisfies(a -> assertThat(a.getPlato()).as("check plato").isEqualTo(expected.getPlato()));
    }
}
