package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static com.mycompany.myapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class FacturaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaAllPropertiesEquals(Factura expected, Factura actual) {
        assertFacturaAutoGeneratedPropertiesEquals(expected, actual);
        assertFacturaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaAllUpdatablePropertiesEquals(Factura expected, Factura actual) {
        assertFacturaUpdatableFieldsEquals(expected, actual);
        assertFacturaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaAutoGeneratedPropertiesEquals(Factura expected, Factura actual) {
        assertThat(actual)
            .as("Verify Factura auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaUpdatableFieldsEquals(Factura expected, Factura actual) {
        assertThat(actual)
            .as("Verify Factura relevant properties")
            .satisfies(a ->
                assertThat(a.getFechaFactura())
                    .as("check fechaFactura")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getFechaFactura())
            )
            .satisfies(a ->
                assertThat(a.getMontoTotal())
                    .as("check montoTotal")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMontoTotal())
            )
            .satisfies(a -> assertThat(a.getMetodoPago()).as("check metodoPago").isEqualTo(expected.getMetodoPago()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaUpdatableRelationshipsEquals(Factura expected, Factura actual) {
        // empty method
    }
}
