package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ItemPedidoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemPedidoAllPropertiesEquals(ItemPedido expected, ItemPedido actual) {
        assertItemPedidoAutoGeneratedPropertiesEquals(expected, actual);
        assertItemPedidoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemPedidoAllUpdatablePropertiesEquals(ItemPedido expected, ItemPedido actual) {
        assertItemPedidoUpdatableFieldsEquals(expected, actual);
        assertItemPedidoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemPedidoAutoGeneratedPropertiesEquals(ItemPedido expected, ItemPedido actual) {
        assertThat(actual)
            .as("Verify ItemPedido auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemPedidoUpdatableFieldsEquals(ItemPedido expected, ItemPedido actual) {
        assertThat(actual)
            .as("Verify ItemPedido relevant properties")
            .satisfies(a -> assertThat(a.getCantidad()).as("check cantidad").isEqualTo(expected.getCantidad()))
            .satisfies(a ->
                assertThat(a.getPrecioUnitario())
                    .as("check precioUnitario")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecioUnitario())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemPedidoUpdatableRelationshipsEquals(ItemPedido expected, ItemPedido actual) {
        assertThat(actual)
            .as("Verify ItemPedido relationships")
            .satisfies(a -> assertThat(a.getPedido()).as("check pedido").isEqualTo(expected.getPedido()));
    }
}
