package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MesaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMesaAllPropertiesEquals(Mesa expected, Mesa actual) {
        assertMesaAutoGeneratedPropertiesEquals(expected, actual);
        assertMesaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMesaAllUpdatablePropertiesEquals(Mesa expected, Mesa actual) {
        assertMesaUpdatableFieldsEquals(expected, actual);
        assertMesaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMesaAutoGeneratedPropertiesEquals(Mesa expected, Mesa actual) {
        assertThat(actual)
            .as("Verify Mesa auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMesaUpdatableFieldsEquals(Mesa expected, Mesa actual) {
        assertThat(actual)
            .as("Verify Mesa relevant properties")
            .satisfies(a -> assertThat(a.getNumero()).as("check numero").isEqualTo(expected.getNumero()))
            .satisfies(a -> assertThat(a.getCapacidad()).as("check capacidad").isEqualTo(expected.getCapacidad()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMesaUpdatableRelationshipsEquals(Mesa expected, Mesa actual) {
        // empty method
    }
}
