package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class PedidoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoAllPropertiesEquals(Pedido expected, Pedido actual) {
        assertPedidoAutoGeneratedPropertiesEquals(expected, actual);
        assertPedidoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoAllUpdatablePropertiesEquals(Pedido expected, Pedido actual) {
        assertPedidoUpdatableFieldsEquals(expected, actual);
        assertPedidoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoAutoGeneratedPropertiesEquals(Pedido expected, Pedido actual) {
        assertThat(actual)
            .as("Verify Pedido auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoUpdatableFieldsEquals(Pedido expected, Pedido actual) {
        assertThat(actual)
            .as("Verify Pedido relevant properties")
            .satisfies(a ->
                assertThat(a.getFechaPedido())
                    .as("check fechaPedido")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getFechaPedido())
            )
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoUpdatableRelationshipsEquals(Pedido expected, Pedido actual) {
        assertThat(actual)
            .as("Verify Pedido relationships")
            .satisfies(a -> assertThat(a.getFactura()).as("check factura").isEqualTo(expected.getFactura()))
            .satisfies(a -> assertThat(a.getMesa()).as("check mesa").isEqualTo(expected.getMesa()));
    }
}
